### PR TITLE
Fix: Only use primary style for top level sections (#554)

### LINKED ISSUE #554: Nested section titles have the same font size
I am using the following `styleguide.config.js`:

```javascript
const { createConfig } = require('@webpack-blocks/webpack2');
const typescript = require('@webpack-blocks/typescript');

module.exports = {
  title: 'Foo Style Guide',
  sections: [
    {
      name: 'Introduction',
      content: 'docs/Introduction.md'
    },
    {
      name: 'Documentation',
      sections: [
        {
          name: 'Sample Section',
          content: 'docs/SampleSection.md'
        },
        {
          name: 'Other Sample Section',
          content: 'docs/OtherSampleSection.md'
        },
      ]
    },
    {
      name: 'UI Components',
      components: 'src/ts/components/**/*.tsx'
    }
  ],
  webpackConfig: createConfig([
    typescript()
  ]),
  resolver: require('react-docgen').resolver.findAllComponentDefinitions,
  propsParser: require('react-docgen-typescript').parse
};
```

I have two nested sections: `Sample Section` and `Other Sample Section`. When my docs get rendered, the titles of these nested sections have the same font size as their parent section titles. I would expect these to be smaller. Is there an easy way I can change that?

### PR DESCRIPTION
**Pull request by dylankiss**
Fixes #554

### CODE REVIEW

File: src/rsg-components/Sections/Sections.js [hunk 1]
```diff
@@ -3,14 +3,15 @@ import PropTypes from 'prop-types';
...
 		<SectionsRenderer>
-			{sections.map((section, idx) => <Section key={idx} section={section} />)}
+			{sections.map((section, idx) => <Section key={idx} section={section} primary={topLevel} />)}
 		</SectionsRenderer>
 	);
 }
 
 Sections.propTypes = {
 	sections: PropTypes.array.isRequired,
+	topLevel: PropTypes.bool,
```
Comment (sapegin) [inline src/rsg-components/Sections/Sections.js]: Maybe `root`?

Comment (dylankiss) [inline src/rsg-components/Sections/Sections.js]: Fine by me. Changed it.

**Comment by sapegin** [comment]
Thanks, merged!
