### PR TITLE
Fix: find() compatibility with IE11

### LINKED ISSUE #899: TypeError: Object doesn't support property or method 'find' in IE
Try run https://github.com/styleguidist/react-styleguidist/tree/master/examples/basic with react-styleguidist@6.5.3

Then open [http://localhost:6060](http://localhost:6060) in IE11.

```
TypeError: Object doesn't support property or method 'find'
    in Preview (created by Playground)
    in div (created by PlaygroundRenderer)
    in div (created by PlaygroundRenderer)
    in PlaygroundRenderer (created by Styled(Playground))
    in Styled(Playground) (created by Playground)
    in Playground (created by Examples)
    in article (created by ExamplesRenderer)
    in ExamplesRenderer (created by Styled(Examples))
    in Styled(Examples) (created by Examples)
    in Examples (created by ReactComponent)
    in div (created by ReactComponentRenderer)
    in ReactComponentRenderer (created by Styled(ReactComponent))
    in Styled(ReactComponent) (created by ReactComponent)
    in ReactComponent (created by Components)
    in div (created by ComponentsRenderer)
    in ComponentsRenderer (created by Components)
    in Components (created by Section)
    in section (created by SectionRenderer)
    in SectionRenderer (created by Styled(Section))
    in Styled(Section) (created by Section)
    in Section (created by Sections)
    in section (created by SectionsRenderer)
    in SectionsRenderer (created by Styled(Sections))
    in Styled(Sections) (created by Sections)
    in Sections (created by StyleGuide)
    in main (created by StyleGuideRenderer)
    in div (created by StyleGuideRenderer)
    in StyleGuideRenderer (created by Styled(StyleGuide))
    in Styled(StyleGuide) (created by StyleGuide)
    in StyleGuide


This may be due to an error in a component you are overriding, or a bug in React Styleguidist.

If you believe this is a bug, please submit an issue.
```

Root cause: Array.prototype.find() is not supported in IE.

https://github.com/styleguidist/react-styleguidist/blob/master/src/utils/splitExampleCode.js#L28
```
	const firstExpression = ast.body.reverse().find(({ type }) => type === 'ExpressionStatement');
```

### PR DESCRIPTION
**Pull request by aabenoja**
Closes #899 

I replaced the `lib/utils/splitExampleCode.js` file in my affected repo with the code built from this change. Everything seems to be working just fine.

### CODE REVIEW

File: src/utils/splitExampleCode.js [hunk 1]
```diff
@@ -25,7 +26,7 @@ export default function splitExampleCode(code) {
 		return { head: '', example: code };
 	}
 
-	const firstExpression = ast.body.reverse().find(({ type }) => type === 'ExpressionStatement');
+	const firstExpression = find(ast.body.reverse(), ({ type }) => type === 'ExpressionStatement');
```
Comment (sapegin) [inline src/utils/splitExampleCode.js]: `find(ast.body.reverse(), { type: 'ExpressionStatement' })` — if we have to use Lodash anyway ;-)

Comment (aabenoja) [reply src/utils/splitExampleCode.js]: I completely forgot about that aspect of lodash. Honestly I just grabbed the first thing that was readily available to me. If there is an alternative I'm more than happy to try it.

**Comment by aabenoja** [comment]
@sapegin Is there anything else I need to add to this PR?

**Comment by sapegin** [comment]
Thanks, merged!
