### PR TITLE
fix(486) - Only show props if there are props

### LINKED ISSUE #486: Do not show Props & Methods tab when there’s no props and methods

### PR DESCRIPTION
**Pull request by SaraVieira**
Closes #486

### CODE REVIEW

File: src/rsg-components/ReactComponent/ReactComponent.js [hunk 1]
```diff
@@ -74,6 +75,7 @@ export default class ReactComponent extends Component {
 						: <ExamplePlaceholder name={name} />
 				}
 				tabButtons={
+					showPropsButton &&
```
Comment (sapegin) [inline src/rsg-components/ReactComponent/ReactComponent.js]: There may be other tabs, not just props. I’m thinking that this may be not that easy to fix ;-)

**Comment by SaraVieira** [comment]
What are the other other tabs?

**Comment by sapegin** [comment]
Doesn’t matter (there are none now) but the `Slot` component can render any number of items. So the props tab button should contain a check if there are props or methods and render null if there are none.

File: src/rsg-components/ReactComponent/ReactComponent.js [hunk 2]
```diff
@@ -44,6 +44,7 @@ export default class ReactComponent extends Component {
 		const { component } = this.props;
 		const { name, slug, pathLine } = component;
 		const { description, examples = [], tags = {} } = component.props;
+		const showPropsButton = component.props.props || (component.props.methods || {}).length > 0;
```
Comment (sapegin) [inline src/rsg-components/ReactComponent/ReactComponent.js]: Also this check won’t work:

* `!![] === true` 
* `({}).length === undefined`

Comment (sapegin) [inline src/rsg-components/ReactComponent/ReactComponent.js]: Here is the right check: https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Usage/Usage.js

**Comment by SaraVieira** [comment]
Didn't know that about the slot but the props button receives the whole props including the methods and props of the component so I updated the code to only show or hide the methods component @sapegin

File: package-lock.json [hunk 3]
```diff
@@ -54,7 +54,7 @@
         "readable-stream": {
           "version": "2.2.11",
           "resolved": "https://registry.npmjs.org/readable-stream/-/readable-stream-2.2.11.tgz",
-          "integrity": "sha512-h+8+r3MKEhkiVrwdKL8aWs1oc1VvBu33ueshOvS26RsZQ3Amhx/oO3TKe4lApSV9ueY6as8EAh7mtuFjdlhg9Q==",
+          "integrity": "sha1-B5azH412iAB/8Lk6gIjTSqF8D3I=",
```
Comment (sapegin) [inline package-lock.json]: Looks like you have some weird version of npm. Why it changes all hashes to SHA1? ;-/

**Comment by sapegin** [comment]
I’ve made some tweaks (see my commits) and merged. Thanks!

**Comment by SaraVieira** [comment]
@sapegin Awesome !
