### PR TITLE
fix(235) - Move open isolated

### LINKED ISSUE #235: New "Open isolated" encroaches on components
monosnap 2016-11-17 08-14-21

Maybe it should just be moved down next to Show code?

### PR DESCRIPTION
**Pull request by SaraVieira**
- Removes open isolated from preview

Fixes #235

### CODE REVIEW

File: src/rsg-components/Playground/PlaygroundRenderer.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import React from 'react';
 import PropTypes from 'prop-types';
+import { MdFullscreen, MdFullscreenExit, MdArrowDropDown, MdArrowDropUp } from 'react-icons/lib/md';
```
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: I think we should import particular icon modules, otherwise we’ll have the whole library in the bundle. And wouldn’t rely on tree shaking in Webpack 2 ;-)

File: src/rsg-components/Playground/PlaygroundRenderer.js [hunk 2]
```diff
@@ -13,51 +14,42 @@ const styles = ({ space, color, fontFamily, fontSize, borderRadius }) => ({
...
-		border: [[1, color.border, 'solid']],
-		borderTop: 0,
-		borderBottomLeftRadius: borderRadius,
-		borderBottomRightRadius: borderRadius,
+		color: color.light,
+		transition: 'all 200ms ease',
 		cursor: 'pointer',
-		'&:hover, &:active': {
-			isolate: false,
+		'&:hover': {
```
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Probably better to disable isolation then to repeat all properties if it doesn’t break anything.

File: src/rsg-components/Playground/PlaygroundRenderer.js [hunk 3]
```diff
@@ -13,51 +14,42 @@ const styles = ({ space, color, fontFamily, fontSize, borderRadius }) => ({
...
 	preview: {
 		marginBottom: space[0],
 		padding: space[2],
 	},
 	codeToggle: {
-		position: 'absolute',
-		right: -1,
-		margin: 0,
-		padding: [[space[0], space[1]]],
+		outline: 'none',
```
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: If you disable default focus styles you need to provide some fallback to make it accessible with a keyboard.

File: src/rsg-components/Playground/PlaygroundRenderer.js [hunk 4]
```diff
@@ -13,51 +14,42 @@ const styles = ({ space, color, fontFamily, fontSize, borderRadius }) => ({
...
 		},
 	},
-	showCode: {
-		composes: '$codeToggle',
-		backgroundColor: color.baseBackground,
-	},
-	hideCode: {
-		composes: '$codeToggle',
-		backgroundColor: color.codeBackground,
+	toolbar: {
```
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: I’d use react-group here ;-)

**Comment by sapegin** [comment]
Should we use a branch for the new UI? I don’t want it to block other features and don’t want to release many small changes separately.

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 4 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: react-group ? What do you mean ?

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 3 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: I will set a focus with the outline , good catch 👍

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 2 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: `isolate: false` what does this do ?

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 1 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: I haven't had problems in importing like this but sure , I can divide this in 4 lines 👍

**Comment by SaraVieira** [comment]
@sapegin I think we should but maybe after this PR goes because this one actually closes an issue

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 2 above)
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: It disables jss-isolate. That’s why you have to copy styles from non-hover state when you don’t have `isolate: false`.

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 4 above)
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: https://sapegin.github.io/react-group/ — we already use it in Styleguidist.

**Comment by sapegin** [comment]
This PR alone creates even more inconsistency with opening / closing isolation ;-|

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 2 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: OHHHHHHHHHHHHHHHHHH

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 3 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Outline added 👍

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 2 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Added 👍

**Comment by SaraVieira** [comment]
@sapegin I can add the same icon at the top , I tought it would be done in phases but I can dp that really quickly 😄

**Comment by sapegin** [comment]
That’s why I want to use a branch, so we could iterate not in production ;-)

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 4 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: But why use react group ?

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 1 above)
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Did you measure bundle size before and after? ;-|

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 4 above)
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Because it’s easy and you could avoid this ugly selector with `:not` ;-)

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 1 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Fixed 👍

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 4 above)
Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: You don't like my css mastery ? :p

**Comment by SaraVieira** [comment]
I created a ui branch and it's pointed to there now 👍

File: src/rsg-components/Playground/PlaygroundRenderer.js (hunk 4 above)
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: 👻

Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Oh , you made this, you selling me your stuff :p

**Comment by SaraVieira** [comment]
Changes made @sapegin

File: src/rsg-components/Playground/PlaygroundRenderer.js [hunk 5]
```diff
@@ -73,8 +74,8 @@ export function PlaygroundRenderer({
 			<div className={classes.preview} data-preview={name ? name : ''}>
 				<Preview code={code} evalInContext={evalInContext} />
 			</div>
-			<section className={classes.toolbar}>
-				<div>
+			<Group separator=" " className={classes.toolbar}>
+				<div className={classes.toolbarItem}>
```
Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Do we still need a margin here? If space isn’t enough then react-group is not the best choice because now we’re mixing spaces (a real space) with margins.

Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: I tried adding only the spaces and they were too close together and you could click one by accident

Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: Then maybe add padding to the button instead of margin to increase clickable area?

Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: The thing is I think it makes sense semantically ( not idea if that is spelled correctly) to have their own margins , that way when something is added it always has that margin associated

Comment (sapegin) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: That’s a tough question ;-) I often keep margins and layout in a separate layer. So do whatever you prefer now and when we extract the button to a separate component we’ll talk again what to do ;-)

Comment (SaraVieira) [inline src/rsg-components/Playground/PlaygroundRenderer.js]: I added a div with a class of toolbarItem arround the component to actually give the margin some abstration from the component :)

**Comment by sapegin** [comment]
I think it’s good enough for the very first iteration, merged, thanks! :shipit:

**Comment by SaraVieira** [comment]
🎉 🎉
